# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "レンス"
subtitle: "Pictures of people and places"
author:  "Joey Wu"
header:
 title: "レンス"
 subtitle: "by Joey Wu"
footer:
 name: "Hello!'"
 bio: "I like taking photos of people and landscapes. Still learning!"
social_urls:
  instagram: "https://www.instagram.com/joeywuuuuu"
  twitter: "https://twitter.com/holeymeister"